# Generated by Django 5.0.6 on 2024-07-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categiria',
            new_name='Categoria',
        ),
    ]
