# Generated by Django 5.0.6 on 2024-08-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_categiria_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
